#!/bin/sh
# postinst script
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)

      sed -i 's|this.selectedAppBox.set_height(0);|//this.selectedAppBox.set_height(0);|g' /usr/share/cinnamon/applets/menu@cinnamon.org/applet.js || true

      RUID=$(who | awk 'FNR == 1 {print $1}')
      rm -f /home/${RUID}/.hamonikr/hamonikr-theme-start.* || true
      rm -f /home/${RUID}/.hamonikr/hamonikr-theme-backup.dconf || true      

      gtk-update-icon-cache || true

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)


    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0